### ISSUE TITLE
[RFC] Deregister and re-register Microbiome packages

### ISSUE THREAD

**Issue by kescobo** [BioJulia/BioJuliaRegistry#53]
I have 3 packages in the BioJulia registry, [`Microbiome.jl`][1], [`MicrobiomePlots.jl`][2], and [`BiobakeryUtils.jl`][3], and ever since I started trying to add `compat` to the dependencies, I've been encountering a bunch of problems. Older versions that didn't have `compat` entries are constantly being installed without me noticing, and leading to a bunch of headaches. 

[1]: https://github.com/BioJulia/Microbiome.jl
[2]: https://github.com/BioJulia/MicrobiomePlots.jl
[3]: https://github.com/BioJulia/BiobakeryUtils.jl

I'm wondering if it would be worth removing all current entries for these packages, and replacing them with new versions that start with the right compatibility entries (actually, I'm thinking of deprecating `MicrobiomePlots` entirely). This would solve a lot of my issues I think. 

## Potential problems

1. Anyone that has recent versions in any Manifests may end up with weird errors trying to instantiate them. I think there are unlikely to be many users (other than me) with these problems, but still worth mentioning
2. The julia General registry needs a PR to cap the dependencies of older versions there to prevent fallbacks there. I don't think this will be hard, and Fredrik said on slack this would likely be accepted.
3. ? anything else?

## Alternative Approach

Could work on fixing the biojulia registry compat entries instead. I could be super simple and conservative (basically do the same thing as in General, but for julia 1.1+). I'm not sure if this actually improves anything re: existing Manifests, but it might be better.

**Comment by CiaranOMara** [comment]
I think it would be useful to have the required compatibility entries in the registry so that running `update` provides a functional set of expected packages. However, manually modifying the registry is risky. Perhaps, as a strategy, a PR with compatibility entries written in expanded form would be less error-prone?

**Comment by kescobo** [comment]
@CiaranOMara Can you expand a bit on what you mean by "expanded form"? I'm not quite sure I follow. And do you mean for these packages in particular, or for the BioJulia registry as a whole?

**Comment by kescobo** [comment]
[I've taken care](https://github.com/JuliaRegistries/General/pull/10262) of (2) above - General now has better bounds for these three packages.

**Comment by CiaranOMara** [comment]
I'm only responding to your case. But, if the strategy has merit, it can certainly be used elsewhere.

For example, below is the current Compat.toml for Microbiome in what I'd call condensed form.
```toml
[0]
julia = "1.1.0-1"

["0.5"]
DataFrames = "0.19"

["0.5-0"]
MultivariateStats = "0.7"

["0.5.1-0"]
Reexport = "0.2"
StatsBase = "0.32"

["0.5.1-0.6.1"]
SpatialEcology = "0.7"

["0.6-0"]
DataFrames = "0.19-0.20"

["0.6.2-0"]
SpatialEcology = "0.9"
```

Below, is an example of what I'd call the expanded form of what's above, where everything is explicitly listed for each release/version (I didn't check for missing `dep` entries). In this form, I think it is easy to see and fill in any gaps. Also, each entry only affects the version under which it is listed -- there are no far-reaching consequences.
```toml
["0.4.1"]
DataFrames = "0.19"
julia = "1.1"

["0.5.0"]
DataFrames = "0.19"
MultivariateStats = "0.7"
SpatialEcology = "0.7"
julia = "1.1"

["0.5.1"]
DataFrames = "0.19"
MultivariateStats = "0.7"
Reexport = "0.2"
SpatialEcology = "0.7"
StatsBase = "0.32"
julia = "1.1"

["0.6.0"]
DataFrames = ["0.19", "0.20"]
MultivariateStats = "0.7"
StatsBase = "0.32"
SpatialEcology = "0.7"
Reexport = "0.2"
julia = "1.1"

["0.6.1"]
DataFrames = ["0.19", "0.20"]
MultivariateStats = "0.7"
StatsBase = "0.32"
SpatialEcology = "0.7"
Reexport = "0.2"
julia = "1.1"

["0.6.2"]
DataFrames = ["0.19", "0.20"]
MultivariateStats = "0.7"
StatsBase = "0.32"
SpatialEcology = "0.9"
Reexport = "0.2"
julia = "1.1"
```

I have to admit, I'm not sure what happens when there is a compatibility overlap: whether something will take precedence or whether an overlap would throw an error. Also, and perhaps most importantly, I don't know whether compatibility bounds set in `general` also apply/carry over to here. ~~If the entries in `general` also apply here, then all of the entries under [0] in `general` overlap with something here.~~

As an aside, I'd be curious to know whether an expanded `compat` would be compressed on the next successful automated/bot register?
